In [2]:

import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

scores:ndarray | None = None # 學生的分數
scores_df:DataFrame | None = None # 學生分數的DataFrame

scores = np.random.randint(50, 101, size=(50, 5))
scores_df = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]
scores_df

     姓名 性別  國文   英文   數學   地理  歷史
1   劉彥宏  男  87   84   83   93  57
2   曾彥廷  男  94  100   56   79  78
3   吳子睿  男  62   71   86   63  62
4   蕭志明  男  68   91   77   61  85
5   王文傑  男  51   51   83   83  93
6   朱冠霖  男  70   50   72   65  82
7   謝欣蓉  女  83  100  100   60  90
8   羅淑芬  女  70   71   82   91  84
9   許美慧  女  95   61   89  100  53
10  廖志豪  男  62   93   53   82  82
11  葉柏翰  男  90   59   93   94  74
12  呂承恩  男  58   77   88   98  67
13  蘇雅婷  女  81   61   50   61  59
14  高浩宇  男  68   68  100   69  87
15  王婉茹  女  56   57   84   80  51
16  莊承翰  男  96   55   77   51  97
17  黃裕傑  男  64   99   91   70  60
18  王冠廷  男  80   85   77   58  72
19  呂婉慧  女  60   90   75   67  87
20  莊子謙  男  78   57   74   54  92
21  蘇彥宏  男  96   67   91   83  57
22  李柏融  男  71   73   86   76  76
23  曾明軒  男  92   83   80   71  50
24  呂佳瑩  女  99   71   53   51  74
25  洪怡君  女  92   94   92   91  61
26  洪柏宏  男  86   54   73   63  99
27  江雅琪  女  74   93   61   96  55
28  郭怡萱  女  59   51   84   64  75
29  簡婉慧  女  62   98   53   56  58
30  楊靜宜  女  79   83   52   60  82
31  曾靜儀  女  91   73   82   51  97
32  蕭怡伶  女  89   87   61   80  66
33  洪裕豪  男  72   97   91   98  76
34  簡建宏  男  62   66   73   74  93
35  劉浩然  男  79   59   75   70  73
36  蕭浩宇  男  53   77   74   63  82
37  呂怡靜  女  54   93   56   90  99
38  邱宗翰  男  51   93  100   88  74
39  彭美慧  女  80   95   53   74  90
40  劉靜芬  女  71   68  100   50  91
41  許淑芬  女  84   56   50   60  80
42  邱裕豪  男  57   86   60   81  94
43  吳雅萍  女  95   86   58   73  85
44  施子軒  男  76   97   68   55  55
45  莊柏融  男  98   87   90   63  99
46  鍾浩銘  男  89   58   91   78  92
47  周美玲  女  52   64   77   62  71
48  劉婉婷  女  79   96   80   54  69
49  曾明哲  男  50   53   63   57  89
50  詹柏翰  男  65   51   55   54  61

In [3]:
import numpy as np
from numpy import ndarray
import pandas as pd
from pandas import DataFrame

scores:ndarray | None = None # 學生的分數
scores_df:DataFrame | None = None # 學生分數的DataFrame

scores = np.random.randint(50, 101, size=(50, 5))
scores_df = pd.DataFrame(scores,            
            columns=['國文', '英文', '數學', '地理', '歷史'],
            index=range(1,51))

names_df:DataFrame = pd.read_csv('students.csv')
scores_df[['姓名','性別']] = names_df[['姓名','性別']].head(n=50).values
scores_df = scores_df[['姓名', '性別','國文', '英文', '數學', '地理', '歷史']]
#選取欄
scores_df[['姓名','國文']]
#選取列
scores_df.iloc[5]
scores_df.iloc[5:10]

     姓名 性別  國文  英文  數學  地理  歷史
6   朱冠霖  男  68  90  71  67  55
7   謝欣蓉  女  55  76  86  99  59
8   羅淑芬  女  52  71  79  73  68
9   許美慧  女  70  64  88  84  77
10  廖志豪  男  96  79  64  99  76